apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mini-pvc-dynamic
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
